### PR TITLE
add PDF properties

### LINKED ISSUE #8: PDF Metadata
I played around with the template locally and noticed that the PDF metadata wasn't embedded in the code. I ended up using something à la
```
\hypersetup{
pdftitle = {Econometrics.jl},
pdfsubject = {JuliaCon 2019 Proceedings},
pdfauthor = {José Bayoán Santiago Calderón},
pdfkeywords = {Julia, Econometrics, Statistical Software, Software Validation}
}
```
I don't know if someone wants to make a PR to pre-fill those values from the YAML file.

### PR DESCRIPTION
**Pull request by matbesancon**
Fixes #8

### CODE REVIEW

**Comment by matbesancon** [comment]
so this will work locally but will not work on the whedon pipeline for now
cc @arfon @vchuravy

**Comment by matbesancon** [comment]
merging it in the pandoc template I guess

**Comment by arfon** [comment]
Heya, sorry for being super-slow to respond here. I think we need to find a way to capture these fields somewhere in the `paper.yml` file so that they don't have to be hard-coded into the Pandoc LaTeX template. Does that make sense?

**Comment by matbesancon** [comment]
Hi @arfon no problem, thing is those fields are redundant with fields already in paper.yml, so they are generated from it (the header.tex is generated)

**Comment by matbesancon** [comment]
it's basically a repetition of the `title{}` and `author{}`

**Pull request merged**
